### ISSUE TITLE
Scrolld.js

### ISSUE THREAD

**Issue by anis-marrouchi** [charliegeiger89/Scrolld.js#1]
I could not find your email on your site, we have added Scrolld.js to our resources list at http://twittstrap.com/resources/index (category javascript),

**Comment by charliegeiger89** [comment]
I knew I forgot something important, thanks for letting me know. I had included it on the jQuery page but nowhere else.

It is now included on the README.md as well as on the scrolldjs.com website.

Feel free to contact me - scrolldjs@gmail.com
